import { ref, uploadBytes } from "firebase/storage";
import { collection, doc, setDoc } from "firebase/firestore";

import { FireDB, FireStorage } from ".";

class PostManager implements IPostManager {
    async uploadToDB(post: Post) {
        // Get collection reference
        const globalCollection = collection(FireDB, "posts");
        // const userPostRef = ...; update global collection and user-specific doc too

        // Create new doc with autogenerated ID
        const postDoc = doc(globalCollection);

        // Upload
        await setDoc(postDoc, post);
    }

    uploadToStorage(uri: string) {
        const storage = ref(FireStorage, "sounds");

        const file = fetch(uri);
    }

    createPost(post: Post): void {
        console.log("Storing", post);

        this.uploadToDB(post);
        this.uploadToStorage(post.audioURI);
    }

    updatingPost(post: Post): void {
        throw new Error("Method not implemented.");
    }
}

export { PostManager };
